Corrected declaration of radial_contact
`radial_contact` was declared as an integer but is being used as a logical.
While intel was happy to interpret .false. and 0 and .true. as 1, gnu is
not so generous. Errors were:

```
 ../../../../MOM6-examples/src/icebergs/src/icebergs_framework.F90:2159:17:

    radial_contact=.false.
                  1
 Warning: Extension: Conversion from LOGICAL(4) to INTEGER(4) at (1)
 ../../../../MOM6-examples/src/icebergs/src/icebergs_framework.F90:2180:21:

        radial_contact=.true. !contact based on berg radii can occur
                      1
 Warning: Extension: Conversion from LOGICAL(4) to INTEGER(4) at (1)
 ../../../../MOM6-examples/src/icebergs/src/icebergs_framework.F90:2192:16:

              if (radial_contact) then
                 1
 Error: IF clause at (1) requires a scalar LOGICAL expression
```